// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Photo struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	Description sql.NullString
	PhotoUrl    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
