// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: photo.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPhoto = `-- name: CreatePhoto :one
INSERT INTO photo (owner_id, description, photo_url)
VALUES ($1, $2, $3)
RETURNING id, owner_id, description, photo_url, created_at, updated_at
`

type CreatePhotoParams struct {
	OwnerID     uuid.UUID
	Description sql.NullString
	PhotoUrl    string
}

func (q *Queries) CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error) {
	row := q.db.QueryRowContext(ctx, createPhoto, arg.OwnerID, arg.Description, arg.PhotoUrl)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Description,
		&i.PhotoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
