// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: photo-metadata.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPhotoMetadata = `-- name: CreatePhotoMetadata :one
INSERT INTO photo_metadata (id, location, created_at)
VALUES ($1, ST_MakePoint($2::double precision, $3::double precision), $4)
RETURNING id, location, created_at
`

type CreatePhotoMetadataParams struct {
	ID        uuid.UUID
	Column2   float64
	Column3   float64
	CreatedAt sql.NullTime
}

func (q *Queries) CreatePhotoMetadata(ctx context.Context, arg CreatePhotoMetadataParams) (PhotoMetadatum, error) {
	row := q.db.QueryRowContext(ctx, createPhotoMetadata,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.CreatedAt,
	)
	var i PhotoMetadatum
	err := row.Scan(&i.ID, &i.Location, &i.CreatedAt)
	return i, err
}
